sdm660-common: rootdir: Create /proc/dt_info on init
So that sensors configurations can be read. Also label it in sepolicy.

01-04 03:37:30.218  1166  1178 E Sensors : sns_reg_conf_la.c(496):/proc/dt_info fopen failed 13
01-04 03:37:30.220  1166  1178 E Sensors : sns_reg_conf_la.c(591):Error open E2P partition 2

Change-Id: I56409edaed644a5b9feeaf7d5a9d1ad997dc6b1c